#!/data/data/com.termux/files/usr/bin/bash

## Penulis : Javas
## Program : mod-jvz uninstall script

## Warna ANSI (Teks & Latar)
RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')" BLACKBG="$(printf '\033[40m')"
DEFAULT_FG="$(printf '\033[39m')"  DEFAULT_BG="$(printf '\033[49m')"

## Direktori
PREFIX='/data/data/com.termux/files/usr'

## Banner
banner () {
    clear
    echo "
    ${BLUE}┌──────────────────────────────────────────────────┐
    ${BLUE}│${RED}░▀█▀░█▀▀░█▀▄░█▄█░█░█░█░█${ORANGE}░░░░░${GREEN}█▀▀░▀█▀░█░█░█░░░█▀▀░░${BLUE}│
    ${BLUE}│${RED}░░█░░█▀▀░█▀▄░█░█░█░█░▄▀▄${ORANGE}░▄▄▄${RED}░${GREEN}▀▀█░░█░░░█░░█░░░█▀▀░░${BLUE}│
    ${BLUE}│${RED}░░▀░░▀▀▀░▀░▀░▀░▀░▀▀▀░▀░▀${ORANGE}░░░░░${GREEN}▀▀▀░░▀░░░▀░░▀▀▀░▀▀▀░░${BLUE}│
    ${BLUE}└──────────────────────────────────────────────────┘
    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Dibuat oleh - Javas"
}

## Jika script dihentikan
exit_on_signal_SIGINT () {
    { printf "\n\n%s\n" "    ${BLUE}[${RED}*${BLUE}] ${RED}Script dibatalkan." 2>&1; echo; reset_color; }
    exit 0
}

exit_on_signal_SIGTERM () {
    { printf "\n\n%s\n" "    ${BLUE}[${RED}*${BLUE}] ${RED}Script dihentikan." 2>&1; echo; reset_color; }
    exit 0
}

trap exit_on_signal_SIGINT SIGINT
trap exit_on_signal_SIGTERM SIGTERM

## Reset warna terminal
reset_color() {
	tput sgr0
	tput op
    return
}

## Proses uninstall
uninstall_modjvz () {
	banner
	if [[ (-L $PREFIX/bin/termux-style) && (-d $PREFIX/share/termux-style) ]]; then
		echo; echo "    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Menghapus mod-jvz (termux-style)..."; echo
		echo "    ${BLUE}[${RED}*${BLUE}] ${RED}Menghapus file dari direktori $PREFIX/share"${BLUE}
		rm -r $PREFIX/share/termux-style $PREFIX/bin/termux-style

		if [[ (! -L $PREFIX/bin/termux-style) && (! -d $PREFIX/share/termux-style) ]]; then
			echo; echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Berhasil dihapus."; echo
			reset_color; exit 0
		else
			echo "    ${BLUE}[${RED}!${BLUE}] ${RED}Terjadi kesalahan saat menghapus."; echo
			reset_color; exit 1
		fi
	else
		echo; echo "    ${BLUE}[${RED}!${BLUE}] ${MAGENTA}mod-jvz ${GREEN}belum terpasang."; echo
		reset_color; exit 0
	fi
}

uninstall_modjvz